spring:
  datasource:
    url: ${url}
    username: ${user}
    password: ${password}
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.ibatis.datasource.pooled.PooledDataSource
mybatis:
  mapper-locations: classpath:dao/*.xml
